#!/bin/bash
set -e
#chown -R 1001:1001 /var/lib/postgresql/data/
POSTGRES_ERP_DB_USER=$(sed 's:/:\\/:g' $POSTGRES_ERP_DB_USER_FILE)
POSTGRES_ERP_DB=$(sed 's:/:\\/:g' $POSTGRES_ERP_DB_FILE)
POSTGRES_ERP_DB_PASSWORD=$(sed 's:/:\\/:g' $POSTGRES_ERP_DB_PASSWORD_FILE)

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE $POSTGRES_ERP_DB;
	CREATE USER $POSTGRES_ERP_DB_USER WITH ENCRYPTED PASSWORD '$POSTGRES_ERP_DB_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_ERP_DB TO $POSTGRES_ERP_DB_USER;
	\connect $POSTGRES_ERP_DB;
	GRANT ALL ON SCHEMA public TO $POSTGRES_ERP_DB_USER;
EOSQL